3 4
3
1
4

3 9
3
1
4

Error de ejecuci√≥n

Detalles: MemoryError During handling of the above exception, 
another exception occurred: 
Traceback (most recent call last): File "/home/forge/code.ticademia.com/storage/app/Main.py", 
line 23, in main() File "/home/forge/code.ticademia.com/storage/app/Main.py", 
line 20, in main findTheKPair(numbers, numbersLst, kIndex) MemoryError